"use strict";

/*
|--------------------------------------------------------------------------
| EmployeeSeeder
|--------------------------------------------------------------------------
|
| Make use of the Factory instance to seed database with dummy data or
| make use of Lucid models directly.
|
*/

/** @type {import('@adonisjs/lucid/src/Factory')} */
const Factory = use("Factory");
const Employee = use("App/Models/Employee");

class EmployeeSeeder {
  async run() {
    await Employee.createMany([
      {
        // MaNhanVien: "NV001",
        user_id: 1,
        // MaPB: "PB01",
        // MaHD: "HD001",
        // MaHeSoLuong: "L10",
        permision_id: 1,
        licensed: 1,
        name: "Phạm Thanh Tùng",
        gender: "FEMALE",

        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",
        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV002",
        user_id: 2,
        permision_id: 1,
        licensed: 1,
        name: "Phạm Thanh Toản",
        gender: "MALE",

        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",
        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV003",
        // MaPB: "PB03",
        // MaHD: "HD003",
        // MaHeSoLuong: "L08",
        user_id: 3,
        permision_id: 2,
        licensed: 1,
        name: "Phạm Thanh Thúy",
        gender: "FEMALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",
        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV004",
        // MaPB: "PB04",
        // MaHD: "HD004",
        // MaHeSoLuong: "L08",
        user_id: 4,
        permision_id: 2,
        licensed: 1,
        name: "Phạm Thanh Tan",
        gender: "FEMALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",
        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV005",
        // MaPB: "PB05",
        // MaHD: "HD005",
        // MaHeSoLuong: "L08",
        user_id: 5,
        permision_id: 2,
        licensed: 1,
        name: "Phạm Thanh Anh",
        gender: "MALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",
        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV006",
        // MaPB: "PB03",
        // MaHD: "HD006",
        // MaHeSoLuong: "L07",
        user_id: 6,
        permision_id: 2,
        licensed: 1,
        name: "Phạm Thanh Công",
        gender: "MALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",
        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV007",
        // MaPB: "PB04",
        // MaHD: "HD007",
        // MaHeSoLuong: "L07",
        user_id: 7,
        permision_id: 3,
        licensed: 1,
        name: "Phạm Thanh Thái",
        gender: "FEMALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",
        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV008",
        // MaPB: "PB03",
        // MaHD: "HD008",
        // MaHeSoLuong: "L06",
        user_id: 8,
        permision_id: 3,
        licensed: 1,
        name: "Phạm Thanh Tĩnh",
        gender: "MALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",
        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV009",
        // MaPB: "PB03",
        // MaHD: "HD009",
        // MaHeSoLuong: "L06",
        user_id: 9,
        permision_id: 3,
        licensed: 1,
        name: "Qoách Tĩnh",
        gender: "MALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",
        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV010",
        // MaPB: "PB03",
        // MaHD: "HD010",
        // MaHeSoLuong: "L06",
        user_id: 10,
        permision_id: 3,
        licensed: 1,
        name: "Hoàng Dung",
        gender: "MALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV011",
        // MaPB: "PB03",
        // MaHD: "HD011",
        // MaHeSoLuong: "L06",
        user_id: 11,
        permision_id: 4,
        licensed: 1,
        name: "Dương Quá",
        gender: "FEMALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV012",
        // MaPB: "PB03",
        // MaHD: "HD012",
        // MaHeSoLuong: "L06",
        user_id: 12,
        permision_id: 4,
        licensed: 1,
        name: "Tiểu Long Nữ",
        gender: "FEMALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV013",
        // MaPB: "PB03",
        // MaHD: "HD013",
        // MaHeSoLuong: "L06",
        user_id: 13,
        permision_id: 4,
        licensed: 1,
        name: "Quan Vân Trường",
        gender: "FEMALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV014",
        // MaPB: "PB03",
        // MaHD: "HD014",
        // MaHeSoLuong: "L06",
        user_id: 14,
        permision_id: 4,
        licensed: 1,
        name: "Lưu Bị",
        gender: "MALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV015",
        // MaPB: "PB03",
        // MaHD: "HD015",
        // MaHeSoLuong: "L06",
        user_id: 15,
        permision_id: 5,
        licensed: 1,
        name: "Tào Tháo",
        gender: "MALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV016",
        // MaPB: "PB04",
        // MaHD: "HD016",
        // MaHeSoLuong: "L06",
        user_id: 16,
        permision_id: 5,
        licensed: 1,
        name: "Tôn Quyền",
        gender: "FEMALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV017",
        // MaPB: "PB04",
        // MaHD: "HD017",
        // MaHeSoLuong: "L06",
        user_id: 17,
        permision_id: 5,
        licensed: 1,
        name: "Công Tôn Sách",
        gender: "MALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV018",
        // MaPB: "PB05",
        // MaHD: "HD018",
        // MaHeSoLuong: "L06",
        user_id: 18,
        permision_id: 5,
        licensed: 1,
        name: "Chu Du",
        gender: "FEMALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV019",
        // MaPB: "PB05",
        // MaHD: "HD019",
        // MaHeSoLuong: "L06",
        user_id: 19,
        permision_id: 5,
        licensed: 1,
        name: "Triệu Vân",
        gender: "MALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV020",
        // MaPB: "PB05",
        // MaHD: "HD020",
        // MaHeSoLuong: "L06",
        user_id: 20,
        permision_id: 5,
        licensed: 1,
        name: "Gia Các Lượng",
        gender: "MALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV021",
        // MaPB: "PB05",
        // MaHD: "HD020",
        // MaHeSoLuong: "L06",
        user_id: 21,
        permision_id: 5,
        licensed: 1,
        name: "Phạm Thanh Tùng",
        gender: "MALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV022",
        // MaPB: "PB05",
        // MaHD: "HD020",
        // MaHeSoLuong: "L06",
        user_id: 22,
        permision_id: 5,
        licensed: 1,
        name: "Phạm Thanh Tùng",
        gender: "MALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV023",
        // MaPB: "PB05",
        // MaHD: "HD020",
        // MaHeSoLuong: "L06",
        user_id: 23,
        permision_id: 6,
        licensed: 1,
        name: "Phạm Thanh Tùng",
        gender: "MALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV024",
        // MaPB: "PB05",
        // MaHD: "HD020",
        // MaHeSoLuong: "L06",
        user_id: 24,
        permision_id: 6,
        licensed: 1,
        name: "Phạm Thanh Tùng",
        gender: "FEMALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV025",
        // MaPB: "PB05",
        // MaHD: "HD020",
        // MaHeSoLuong: "L06",
        user_id: 25,
        permision_id: 6,
        licensed: 1,
        name: "Phạm Thanh Tùng",
        gender: "MALE",

        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV026",
        // MaPB: "PB05",
        // MaHD: "HD020",
        // MaHeSoLuong: "L06",
        user_id: 26,
        permision_id: 6,
        licensed: 1,
        name: "Phạm Thanh Tùng",
        gender: "MALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV027",
        // MaPB: "PB05",
        // MaHD: "HD020",
        // MaHeSoLuong: "L06",
        user_id: 27,
        permision_id: 6,
        licensed: 1,
        name: "Phạm Thanh Tùng",
        gender: "FEMALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV028",
        // MaPB: "PB05",
        // MaHD: "HD020",
        // MaHeSoLuong: "L06",
        user_id: 28,
        permision_id: 6,
        licensed: 1,
        name: "Phạm Thanh Tùng",
        gender: "MALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV029",
        // MaPB: "PB05",
        // MaHD: "HD020",
        // MaHeSoLuong: "L06",
        user_id: 29,
        permision_id: 6,
        licensed: 1,
        name: "Phạm Thanh Tùng",
        gender: "FEMALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV030",
        // MaPB: "PB05",
        // MaHD: "HD020",
        // MaHeSoLuong: "L06",
        user_id: 30,
        permision_id: 6,
        licensed: 1,
        name: "Phạm Thanh Tùng",
        gender: "MALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV031",
        // MaPB: "PB05",
        // MaHD: "HD020",
        // MaHeSoLuong: "L06",
        user_id: 31,
        permision_id: 6,
        licensed: 1,
        name: "Phạm Thanh Tùng",
        gender: "MALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV032",
        // MaPB: "PB05",
        // MaHD: "HD020",
        // MaHeSoLuong: "L06",
        user_id: 32,
        permision_id: 6,
        licensed: 1,
        name: "Phạm Thanh Tùng",
        gender: "FEMALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV033",
        // MaPB: "PB05",
        // MaHD: "HD020",
        // MaHeSoLuong: "L06",
        user_id: 33,
        permision_id: 6,
        licensed: 1,
        name: "Phạm Thanh Tùng",
        gender: "MALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV034",
        // MaPB: "PB05",
        // MaHD: "HD020",
        // MaHeSoLuong: "L06",
        user_id: 34,
        permision_id: 6,
        licensed: 1,
        name: "Phạm Thanh Tùng",
        gender: "FEMALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV035",
        // MaPB: "PB05",
        // MaHD: "HD020",
        // MaHeSoLuong: "L06",
        user_id: 35,
        permision_id: 6,
        licensed: 1,
        name: "Phạm Thanh Tùng",
        gender: "MALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV036",
        // MaPB: "PB05",
        // MaHD: "HD020",
        // MaHeSoLuong: "L06",
        user_id: 36,
        permision_id: 6,
        licensed: 1,
        name: "Phạm Thanh Tùng",
        gender: "MALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV037",
        // MaPB: "PB05",
        // MaHD: "HD020",
        // MaHeSoLuong: "L06",
        user_id: 37,
        permision_id: 6,
        licensed: 1,
        name: "Phạm Thanh Tùng",
        gender: "FEMALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV038",
        // MaPB: "PB05",
        // MaHD: "HD020",
        // MaHeSoLuong: "L06",
        user_id: 38,
        permision_id: 6,
        licensed: 1,
        name: "Phạm Thanh Tùng",
        gender: "MALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV039",
        // MaPB: "PB05",
        // MaHD: "HD020",
        // MaHeSoLuong: "L06",
        user_id: 39,
        permision_id: 6,
        licensed: 1,
        name: "Phạm Thanh Tùng",
        gender: "FEMALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      },
      {
        // MaNhanVien: "NV040",
        // MaPB: "PB05",
        // MaHD: "HD020",
        // MaHeSoLuong: "L06",
        user_id: 40,
        permision_id: 6,
        licensed: 1,
        name: "Phạm Thanh Tùng",
        gender: "FEMALE",
        day_of_birth: "1998-08-11",
        identity_card_number: "8888888888",
        phone_number: "0123456789",

        address: "Hồ Chí Minh",
        native_place: "Hà Nội",
        nationality: "Kinh",
        email: "@gmail.com",
        marital_status: "Độc Thân",
        avatar: "img/avatars/hinhnhanvien.jpg",
        fingerprint_image: "vantay/hinhvantay.png"
      }
    ]);
  }
}

module.exports = EmployeeSeeder;
